// calculator-reactts-hooks/src/calculator/calculator.tsx
import * as React from 'react';

import { CalculatorButton } from './calculator-button/calculator-button';
import { CalculatorDisplay } from './calculator-display/calculator-display';
import { ICalculatorLogic } from './logic/calculator-logic/icalculator-logic';

import './styles.scss';

/**
 * Component props.
 * @property {ICalculatorLogic} calculatorLogic - calculator logic provider.
 */
type TProps = {
  calculatorLogic: ICalculatorLogic;
};

/**
 * Calculator component.
 * @return {JSX.Element} component render.
 */
export function Calculator(props: TProps): JSX.Element {
  const [value, setValue]: [string, (value: string) => void] = React.useState('0');

  const clickButton: (event: React.MouseEvent) => void = (event: React.MouseEvent): void => {
    setValue(props.calculatorLogic.handleInput((event.target as HTMLElement).innerText));
  };

  const pressedKey: (event: React.KeyboardEvent) => void = (event: React.KeyboardEvent): void => {
    if ('Enter' === event.key || ' ' === event.key) {
      if (event.target && event.target instanceof HTMLElement) {
        setValue(props.calculatorLogic.handleInput((event.target as HTMLElement).innerText));
      }
    }
  };

  // button definitions
  const buttons: {id: number, cap: string; classes: string}[] = [{
    id: 0,
    classes: 'calculator__element calculator__element--value calculator__element--small calculator__element--cell-clear',
    cap: 'clear'
  }, {
    id: 1,
    classes: 'calculator__element calculator__element--action calculator__element--cell-divide',
    cap: '\u00f7'
  }, {
    id: 2,
    classes: 'calculator__element calculator__element--value calculator__element--cell-seven',
    cap: '7'
  }, {
    id: 3,
    classes: 'calculator__element calculator__element--value calculator__element--cell-eight',
    cap: '8'
  }, {
    id: 4,
    classes: 'calculator__element calculator__element--value calculator__element--cell-nine',
    cap: '9'
  }, {
    id: 5,
    classes: 'calculator__element calculator__element--action calculator__element--cell-multiply',
    cap: 'x'
  }, {
    id: 6,
    classes: 'calculator__element calculator__element--value calculator__element--cell-four',
    cap: '4'
  }, {
    id: 7,
    classes: 'calculator__element calculator__element--value calculator__element--cell-five',
    cap: '5'
  }, {
    id: 8,
    classes: 'calculator__element calculator__element--value calculator__element--cell-six',
    cap: '6'
  }, {
    id: 9,
    classes: 'calculator__element calculator__element--action calculator__element--cell-subtract',
    cap: '-'
  }, {
    id: 10,
    classes: 'calculator__element calculator__element--value calculator__element--cell-one',
    cap: '1'
  }, {
    id: 11,
    classes: 'calculator__element calculator__element--value calculator__element--cell-two',
    cap: '2'
  }, {
    id: 12,
    classes: 'calculator__element calculator__element--value calculator__element--cell-three',
    cap: '3'
  }, {
    id: 13,
    classes: 'calculator__element calculator__element--action calculator__element--cell-plus',
    cap: '+'
  }, {
    id: 14,
    classes: 'calculator__element calculator__element--value calculator__element--cell-zero',
    cap: '0'
  }, {
    id: 15,
    classes: 'calculator__element calculator__element--action calculator__element--cell-equal',
    cap: '='
  }];

  return (
    <section className="calculator">
      <CalculatorDisplay
        className="calculator__element calculator__element--cell-display"
        value={ value }/>

      {buttons.map((button: {id: number; cap: string; classes: string}, index: number) => (
        <CalculatorButton
          key={ button.id }
          tabIndex={ index + 1 }
          className={ button.classes }
          cap={ button.cap }
          clickHandler={ clickButton }
          keyHandler={ pressedKey }                  
        />
      ))}
    </section>
  );
}

// calculator-angular/src/app/calculator/calculator.component.ts
import { Component, OnInit } from '@angular/core';

import { CalculatorLogicService } from '../core/calculator-logic.service';

/**
 * Calculator component.
 */
@Component({
  selector: 'app-calculator',
  templateUrl: './calculator.component.html',
  styleUrls: ['./calculator.component.scss']
})
export class CalculatorComponent implements OnInit {
  // @member {{cap: string; classes: string}[]} buttons - list of buttons to build the calculator UI.
  public buttons: {cap: string; classes: string}[] = [];

  // @member {string} value - current value display on the calculator.
  public value: string = '0';

  /**
   * Constructor.
   * @param {CalculatorLogicService} calculatorLogic - calculator logic service provider.
   */
  public constructor(private calculatorLogic: CalculatorLogicService) {
    // button definitions
    this.buttons = [{
      classes: 'calculator__element calculator__element--value calculator__element--three-wide calculator__element--small',
      cap: 'clear'
    }, {
      classes: 'calculator__element calculator__element--action',
      cap: '\u00f7'
    }, {
      classes: 'calculator__element calculator__element--value',
      cap: '7'
    }, {
      classes: 'calculator__element calculator__element--value',
      cap: '8'
    }, {
      classes: 'calculator__element calculator__element--value',
      cap: '9'
    }, {
      classes: 'calculator__element calculator__element--action',
      cap: 'x'
    }, {
      classes: 'calculator__element calculator__element--value',
      cap: '4'
    }, {
      classes: 'calculator__element calculator__element--value',
      cap: '5'
    }, {
      classes: 'calculator__element calculator__element--value',
      cap: '6'
    }, {
      classes: 'calculator__element calculator__element--action',
      cap: '-'
    }, {
      classes: 'calculator__element calculator__element--value',
      cap: '1'
    }, {
      classes: 'calculator__element calculator__element--value',
      cap: '2'
    }, {
      classes: 'calculator__element calculator__element--value',
      cap: '3'
    }, {
      classes: 'calculator__element calculator__element--action',
      cap: '+'
    }, {
      classes: 'calculator__element calculator__element--value calculator__element--three-wide',
      cap: '0'
    }, {
      classes: 'calculator__element calculator__element--action',
      cap: '='
    }];
  }

  /**
   * On init lifecycle.
   */
  public ngOnInit(): void {
  }

  /**
   * Handle mouse click event.
   * @param {MouseEvent} event - event that occured.
   */
  public clickButton(event: MouseEvent): void {
    // pass element that was clicked to input handler
    this.value = this.calculatorLogic.handleInput((event.target as HTMLElement).innerText);
  }

  /**
   * Handle keyboard selection event ( space or enter ).
   * @param {KeyboardEvent} event - event that occurred,
   */
  public pressedKey(event: KeyboardEvent): void {
    if ('Enter' === event.key || ' ' === event.key) {
      if (event.target && event.target instanceof HTMLElement) {
        this.value = this.calculatorLogic.handleInput((event.target as HTMLElement).innerText);
      }
    }
  }
}

<section class="calculator">
  <app-calculator-display class="calculator__element calculator__element--four-wide" ></app-calculator-display>

  <!-- clear  -->
  <app-calculator-button class="calculator__element calculator__element--value calculator__element--three-wide calculator__element--small" cap="clear"></app-calculator-button>
  <!-- divide -->
  <app-calculator-button cap="&divide;" class="calculator__element calculator__element--action"></app-calculator-button>
  <!-- 7 -->
  <app-calculator-button cap="7" class="calculator__element calculator__element--value"></app-calculator-button>
  <!-- 8 -->
  <app-calculator-button cap="8" class="calculator__element calculator__element--value"></app-calculator-button>
  <!-- 9 -->
  <app-calculator-button cap="9" class="calculator__element calculator__element--value"></app-calculator-button>
  <!-- subtract -->
  <app-calculator-button cap="-" class="calculator__element calculator__element--action"></app-calculator-button>
  <!-- 4 -->
  <app-calculator-button cap="4" class="calculator__element calculator__element--value"></app-calculator-button>
  <!-- 5 -->
  <app-calculator-button cap="5" class="calculator__element calculator__element--value"></app-calculator-button>
  <!-- 6 -->
  <app-calculator-button cap="6" class="calculator__element calculator__element--value"></app-calculator-button>
  <!-- plus -->
  <app-calculator-button cap="+" class="calculator__element calculator__element--action"></app-calculator-button>
  <!-- 1 -->
  <app-calculator-button cap="1" class="calculator__element calculator__element--value"></app-calculator-button>
  <!-- 2 -->
  <app-calculator-button cap="2" class="calculator__element calculator__element--value"></app-calculator-button>
  <!-- 3 -->
  <app-calculator-button cap="3" class="calculator__element calculator__element--value"></app-calculator-button>
  <!-- total -->
  <app-calculator-button cap="=" class="calculator__element calculator__element--action"></app-calculator-button>
</section>
